### ISSUE TITLE
Libevent updated 2.1.10-1 -> 2.1.11-1

### ISSUE THREAD

**Issue by michaldybczak** [Thaodan/thaopkgs#2]
Because the libevent update I get:

```
XPCOMGlueLoad error for file /usr/lib/firefox/libxul.so:
libevent-2.1.so.6: cannot open shared object file: No such file or directory
Couldn't load XPCOM.
```
and FF won't start.

Seems like it needs to be recompiled.

**Comment by Thaodan** [comment]
First please open bugs not here, see the AUR page for more.
2nd: its ok to make a comment on the AUR page thats ok but 
don't open a bug here for such things like this. I need to 
rebuilt the package and my real live comes first so please 
wait.

I you have any input or want to donate to keep my server 
running feel free to drop me a line.

**Comment by michaldybczak** [comment]
Sorry for making you feel rushed. That was not my intention. I was just informing. Take as much time as you need. I will be using Plasmafox instead so I'm good. I'm aware I can create symlink to bypass this problem, but that's a hacky solution and I will forget that I put that symlink, so I'd rather keep my system clean and wait.

I'll remember to post such trivial things on the AUR page in the future.

I just thought that the AUR version in for us to compile, while repo offers binaries and is a separate thing so I post it elsewhere and as I said in the past, gitlab sucks big time and I will not span any new accounts for everything I want to report (I rather ignore and won't give any feedback). Github, on the other hand, is great. An easy and clear system for issues, one account, hence this felt like the only place where I can post such things.

If some other issue arises that needs bugfixing, I will post it here either way, because we don't have any other reasonable place to do so and on github at least you can keep track and close it when it's done.
