### ISSUE TITLE
No firefox update, package obsolete - won't work, need recompilation

### ISSUE THREAD

**Issue by michaldybczak** [Thaodan/thaopkgs#5]
Today's update rendered firefox-kde-opensuse useless. I got:

```
XPCOMGlueLoad error for file /usr/lib/firefox/libxul.so:
libdav1d.so.3: cannot open shared object file: No such file or directory
Couldn't load XPCOM.
```

Sure, I could probably fix it by creating some workaround symlinks, but that is a bad solution, because I will just forget about the symlink and the clutter on root starts to build.

The main issue is, there was no firefox-kde-opensuse updates since a long time. The last update was on 23rd of January and in meantime there were important security fixes. Is this package abandoned? We have now not insecure, obsolete and not working package.
What happened?

Thanks for the answer,

Mike

**Comment by michaldybczak** [comment]
I assume that since the topic is closed, FF was updated? It took so long, I had to migrate onto different package firefox-appemnu-bin.

**Comment by Thaodan** [comment]
It was and is. FF 77 was already updated to beta and I'm building the release version now.

**Comment by Thaodan** [comment]
See the commit history why it took so long and what took so long.

**Comment by michaldybczak** [comment]
Ah, OK. Thanks for the info.
